name: 'Publish package'

on:
  workflow_call:
    secrets:
      BOT_ACCESS_KEY:
        required: true
        description: 'AWS Access Key Id'
      BOT_SECRET_KEY:
        required: true
        description: 'AWS Secret Access Key'
      S3_BUCKET:
        required: true
        description: 'AWS S3 Bucket to upload to'
      AWS_REGION:
        required: true
        description: 'AWS Region the S3 Bucket is located in'

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: 'Checkout feature branch'
        uses: actions/checkout@v2
        with:
          path: 'feature'

      - name: 'Prepare packages for archiving'
        id: move_packages
        uses: dhis2-metadata/prepare@DEVOPS-124
        with:
          working_dir: 'feature'

      - name: 'Checkout master branch'
        uses: actions/checkout@v2
        with:
          ref: 'master'
          path: 'master'

      - name: 'Move installation guide to archive dir'
        run: sudo cp docs/installation.md "../${{ steps.move_packages.outputs.archive_dir }}"
        working-directory: 'master'

      - name: 'Archive packages'
        run: zip -r "${{ steps.move_packages.outputs.archive_dir }}.zip" ${{ steps.move_packages.outputs.archive_dir }}

      - name: 'Upload packages archive'
        uses: prewk/s3-cp-action@v2
        with:
          aws_access_key_id: ${{ secrets.BOT_ACCESS_KEY }}
          aws_secret_access_key: ${{ secrets.BOT_SECRET_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          source: "${{ steps.move_packages.outputs.archive_dir }}.zip"
          dest: "s3://${{ secrets.S3_BUCKET }}/${{ steps.move_packages.outputs.destination }}/${{ steps.move_packages.outputs.archive_dir }}.zip"
          flags: --acl public-read
