name: 'Publish package'

on:
  workflow_call:
    secrets:
      BOT_ACCESS_KEY:
        required: true
        description: 'AWS Access Key Id'
      BOT_SECRET_KEY:
        required: true
        description: 'AWS Secret Access Key'
      S3_BUCKET:
        required: true
        description: 'AWS S3 Bucket to upload to'
      AWS_REGION:
        required: true
        description: 'AWS Region the S3 Bucket is located in'
      BOT_GITHUB_PAT:
        required: true
        description: 'GitHub Personal Access Token for updating Packages Downloads index repo'
      BOT_GITHUB_EMAIL:
        required: true
        description: 'GitHub Email for updating Packages Downloads index repo'

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: 'Checkout feature branch'
        uses: actions/checkout@v3
        with:
          path: 'feature'

      - name: 'Get Package and DHIS2 versions from tag'
        id: get_versions
        run: |
          VERSIONS="${GITHUB_REF_NAME#D}"
          PACKAGE_VERSION="${VERSIONS#*/}"
          DHIS2_VERSION="${VERSIONS%/*}"

          echo "package_version=$PACKAGE_VERSION" >> $GITHUB_OUTPUT
          echo "dhis2_version=$DHIS2_VERSION" >> $GITHUB_OUTPUT

      - name: 'Prepare packages for archiving'
        id: move_packages
        uses: dhis2-metadata/prepare@v1
        with:
          working_dir: 'feature'
          package_version: ${{ steps.get_versions.outputs.package_version }}

      - name: 'Generate S3 destination path'
        id: generate_s3_destination
        run: |
          PACKAGE_S3_PREFIX="${{ steps.move_packages.outputs.package_locale }}\
          /${{ steps.move_packages.outputs.package_base_code }}\
          /${{ steps.get_versions.outputs.package_version }}\
          /DHIS${{ steps.get_versions.outputs.dhis2_version }}"

          echo "package_s3_prefix=$PACKAGE_S3_PREFIX" >> $GITHUB_OUTPUT

      - name: 'Generate package reference files'
        id: generate_reference_files
        run: |
          npm install dev-otta/metadatareference

          packages=($(find ${{ steps.move_packages.outputs.archive_dir }} -type f -name "*.json" | sort))
          
          mkdir reference-files

          for package_path in "${packages[@]}"
          do
            cd "$GITHUB_WORKSPACE/$(dirname $package_path)"

            package_name=$(basename $package_path)

            sudo node $GITHUB_WORKSPACE/node_modules/metadatareference/reference.js $package_name

            cp "${package_name%.*}.xlsx" "$GITHUB_WORKSPACE/reference-files/"
          done

      - name: 'Checkout master branch'
        uses: actions/checkout@v3
        with:
          ref: 'master'
          path: 'master'

      - name: 'Convert installation guide to PDF'
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_path: master/docs
          output_dir: master/docs/pdfs
          build_html: false

      - name: 'Move installation guide to archive dir'
        working-directory: 'master'
        run: |
          for file in docs/pdfs/*installation.pdf
          do
            file_name="$(basename $file)"
            sudo mv "$file" "../${{ steps.move_packages.outputs.archive_dir }}/${file_name%.pdf}-v${{ steps.get_versions.outputs.package_version }}.pdf"
          done

      - name: 'Archive packages'
        run: sudo zip -r "${{ steps.move_packages.outputs.archive_dir }}.zip" ${{ steps.move_packages.outputs.archive_dir }}

      - name: 'Upload packages archive'
        uses: prewk/s3-cp-action@v2
        with:
          aws_access_key_id: ${{ secrets.BOT_ACCESS_KEY }}
          aws_secret_access_key: ${{ secrets.BOT_SECRET_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          source: "${{ steps.move_packages.outputs.archive_dir }}.zip"
          dest: "s3://${{ secrets.S3_BUCKET }}\
            /${{ steps.generate_s3_destination.outputs.package_s3_prefix }}\
            /${{ steps.move_packages.outputs.archive_dir }}.zip"

      - name: 'Upload all reference files next to archive'
        uses: prewk/s3-cp-action@v2
        with:
          aws_access_key_id: ${{ secrets.BOT_ACCESS_KEY }}
          aws_secret_access_key: ${{ secrets.BOT_SECRET_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          source: "reference-files/"
          dest: "s3://${{ secrets.S3_BUCKET }}\
            /${{ steps.generate_s3_destination.outputs.package_s3_prefix }}/"
          flags: --recursive

      - name: 'Checkout Downloads index'
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.BOT_GITHUB_PAT }}
          repository: 'dhis2-metadata/downloads-index'
          path: 'downloads-index'

      - name: 'Checkout Downloads index updater'
        uses: actions/checkout@v3
        with:
          repository: 'dhis2-metadata/downloads-index-updater'
          path: 'downloads-index-updater'

      - name: 'Update downloads index.json'
        run: |
          echo Updating downloads index.json

          cd downloads-index-updater

          VERSIONED_PACKAGE_FILE_NAME="${{ steps.move_packages.outputs.package_code }}_${{ steps.get_versions.outputs.package_version }}_DHIS${{ steps.get_versions.outputs.dhis2_version }}"

          VERSIONED_PACKAGE_FILE_PATH="${{ steps.move_packages.outputs.archive_dir }}/$VERSIONED_PACKAGE_FILE_NAME/$VERSIONED_PACKAGE_FILE_NAME.json"

          ls -la ../$VERSIONED_PACKAGE_FILE_PATH

          python3 update_index.py \
            --package "$(sudo cat ../$VERSIONED_PACKAGE_FILE_PATH | jq -r '.package')" \
            --index-file ../downloads-index/index.json \
            --release-date "$(date +'%Y-%m-%d')" \
            --url "https://packages.dhis2.org/${{ steps.generate_s3_destination.outputs.package_s3_prefix }}/${{ steps.move_packages.outputs.archive_dir }}.zip" \
            --reference-url "https://packages.dhis2.org/${{ steps.generate_s3_destination.outputs.package_s3_prefix }}/$VERSIONED_PACKAGE_FILE_NAME.xlsx"

      - name: 'Push updated Packages Download index'
        run: |
          cd downloads-index

          git config user.email ${{ secrets.BOT_GITHUB_EMAIL }}
          git config user.name dhis2-bot

          BRANCH_NAME="update-${{ steps.move_packages.outputs.package_base_code }}-${{ steps.get_versions.outputs.package_version }}-${{ steps.get_versions.outputs.dhis2_version }}"

          git checkout -b $BRANCH_NAME

          git add index.json

          if [[ -n "$(git status --porcelain)" ]]; then
            git commit -m "chore: update index with ${{ steps.move_packages.outputs.package_base_code }} v${{ steps.get_versions.outputs.package_version }}, DHIS2 v${{ steps.get_versions.outputs.dhis2_version }}"
            git push origin $BRANCH_NAME
            gh pr create --base master --head $BRANCH_NAME --fill --reviewer stratosilva,yuryrog
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_PAT }}

      - name: 'Get Release notes'
        uses: yashanand1910/standard-release-notes@v1.2.1
        id: get_release_notes
        with:
          changelog_path: master/docs/release_note.md
          version: ${{ steps.get_versions.outputs.package_version }}

      - name: 'Find release ID'
        id: find_release
        uses: cardinalby/git-get-release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ github.ref_name }}

      - name: 'Update Release description'
        uses: irongut/editrelease@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          id: ${{ steps.find_release.outputs.id }}
          body: "Package uploaded to https://${{ secrets.S3_BUCKET }}\
            /${{ steps.generate_s3_destination.outputs.package_s3_prefix }}\
            /${{ steps.move_packages.outputs.archive_dir }}.zip\n\n\
            ${{ steps.get_release_notes.outputs.release_notes }}"
